CREATE TABLE ingrediente (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    quantidade BIGINT(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;