CREATE TABLE comprador (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	inscricao BIGINT(14) NOT NULL,
	logradouro VARCHAR(100) NOT NULL,
	numero BIGINT(5) NOT NULL,
	bairro VARCHAR(50) NOT NULL,
	cidade VARCHAR(50) NOT NULL,
	estado VARCHAR(50) NOT NULL,
	pais VARCHAR(50) NOT NULL,
	cep BIGINT(7)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;